"use strict";
exports.__esModule = true;
var singly_list_1 = require("./structures/singly-linked-list");
var instance = new singly_list_1.SinglyLinkedList();
instance.push(24);
instance.push(12);
instance.push(23);
instance.push(26);
instance.push(89);
instance.push(10);
console.log(instance);
